### ISSUE TITLE
add integration tests for a11y components

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Components#2]

**Comment by qunabu** [comment]
![IMG_20220519_160053](https://user-images.githubusercontent.com/214608/169369102-cae74d7a-cd18-4dd9-b535-57e434b7e66c.jpeg)

**Comment by pieecia** [comment]
> [responsive](https://react-styleguidist.js.org/docs/cookbook#how-to-use-react-axe-to-test-accessibility-of-components)

which package do you think we should use? `axe-core/react` or `jest-axe`?
